version: 2.1
setup: true
orbs:
  orb-tools: circleci/orb-tools@12.0
  shellcheck: circleci/shellcheck@3.1

filters: &filters
  tags:
    only: /.*/

workflows:
  lint-pack:
    jobs:
      - orb-tools/lint:
          filters: *filters
          resource_class: small
      - orb-tools/pack:
          filters: *filters
          resource_class: small
      - orb-tools/review:
          exclude: "RC009,RC010"
          filters: *filters
          resource_class: small
      - shellcheck/check:
          filters: *filters
          resource_class: small
      - orb-tools/publish:
          name: DEV publish
          orb_name: coingaming/trading-team-orb
          vcs_type: << pipeline.project.type >>
          pub_type: dev
          resource_class: small
          requires:
            [orb-tools/lint, orb-tools/review, orb-tools/pack, shellcheck/check]
          # Use a context to hold your publishing token.
          context: trading
          filters: *filters
      # Triggers the next workflow in the Orb Development Kit.
      - orb-tools/continue:
          pipeline_number: << pipeline.number >>
          vcs_type: << pipeline.project.type >>
          orb_name: trading-team-orb
          resource_class: small
          requires:
            - DEV publish
          filters: *filters