description: >
  Runs Solution Build

executor:
  name: default
  tag: <<parameters.builder_image_tag>>

parameters:
  solution_path:
    description: Path to csproj file relative to project root
    type: string
  sonarscanner_project_key:
    description: Project Key For SonarScanner
    type: string
  builder_image_tag:
    default: '3.1'
    description: Tag of builder image
    type: string

steps:
  - checkout
  - build_solution:
      solution_path: <<parameters.solution_path>>
      sonarscanner_project_key: <<parameters.sonarscanner_project_key>>
  - persist_to_workspace:
      root: ./
      paths:
        - .
