description: >
  Runs Solution Build

executor:
  name: default
  tag: <<parameters.builder_image_tag>>
  resource_class: <<parameters.executor_class>>

parameters:
  builder_image_tag:
    default: '3.1'
    description: Tag of builder image
    type: string
  executor_class:
    default: 'medium'
    type: string
  solution_path:
    description: Path to csproj file relative to project root
    type: string
  run_marten_codegen:
    default: false
    description: Set this to true for projects that implement code generation for Marten
    type: boolean

steps:
  - checkout
  - build_solution:
      solution_path: <<parameters.solution_path>>
      run_marten_codegen: <<parameters.run_marten_codegen>>
  - persist_to_workspace:
      root: ./
      paths:
        - .
  - inject_slack_templates
  - slack/notify:
      event: fail
      template: BUILD_FAILED_TEMPLATE
      channel: odds88-circleci-notifications
