description: >
  Default build executor
docker:
  - image: 'public.ecr.aws/y7n1s6r0/trading-dev-core-sdk:<<parameters.tag>>'
working_directory: /mnt/ramdisk
parameters:
  tag:
    default: '3.1'
    description: >
      Pick a specific image tag:
      https://gallery.ecr.aws/y7n1s6r0/trading-dev-core-sdk
    type: string
